import { useNavigate } from "react-router-dom";
import { useEffect } from "react";
import { useAuth } from "@/hooks/useAuth";
import { useUserRole } from "@/hooks/useUserRole";
import { useBrandAccount } from "@/hooks/useBrandAccount";
import { BrandLayout } from "@/components/layout/BrandLayout";
import { Card, CardContent } from "@/components/ui/card";
import { motion } from "framer-motion";
import {
  ArrowRight,
  LayoutDashboard,
  Users,
  MessageSquare,
  Gift,
  AtSign,
  CreditCard,
  Settings,
  HelpCircle,
  Loader2,
  Mail,
} from "lucide-react";

const guides = [
  {
    icon: LayoutDashboard,
    title: "Getting Started",
    description: "Set up your brand and start connecting with creators",
    items: [
      "Complete your brand profile with logo, description, and website",
      "Browse the Creator Directory to find creators that match your brand",
      "Send connection requests or respond to inbound creator requests",
      "Use Messages to communicate directly with creators",
    ],
  },
  {
    icon: Users,
    title: "Creator Directory",
    description: "Finding and managing creator relationships",
    items: [
      "Search and filter creators by niche, follower count, and engagement",
      "View detailed creator profiles including audience demographics",
      "Send collaboration invitations directly from creator profiles",
      "Track your active creator partnerships from the dashboard",
    ],
  },
  {
    icon: MessageSquare,
    title: "Messages",
    description: "Communicating with creators",
    items: [
      "View inbound requests from creators in the My Requests tab",
      "Send discount codes, gift offers, and mention requests via message cards",
      "Keep all collaboration discussions in one organised thread",
      "Receive notifications when creators respond to your messages",
    ],
  },
  {
    icon: Gift,
    title: "Gifting",
    description: "Managing PR sends and product seeding",
    items: [
      "Create gifting campaigns to send products to selected creators",
      "Track shipment status and creator acknowledgements",
      "Set campaign goals and measure results",
      "Manage your gifting budget and inventory allocation",
    ],
  },
  {
    icon: AtSign,
    title: "Mentions",
    description: "Tracking creator content and brand mentions",
    items: [
      "Create mention campaigns with specific content briefs",
      "Track when creators post content mentioning your brand",
      "Review and approve creator content before it goes live",
      "Measure the reach and engagement of creator mentions",
    ],
  },
  {
    icon: CreditCard,
    title: "Payments",
    description: "Managing creator payments and billing",
    items: [
      "View your payment history and outstanding balances",
      "Top up your brand balance via EFT or card",
      "Track payments made to individual creators",
      "Download invoices and payment receipts",
    ],
  },
  {
    icon: Settings,
    title: "Brand Settings",
    description: "Managing your brand account",
    items: [
      "Update your brand profile, logo, and description",
      "Manage team members and permissions",
      "Configure notification preferences",
      "View your subscription plan and billing details",
    ],
  },
];

const faqs = [
  {
    q: "How do I invite a creator to collaborate?",
    a: "Go to the Creator Directory, find a creator you'd like to work with, and click their profile to send a collaboration request. You can also message them directly.",
  },
  {
    q: "How do payments to creators work?",
    a: "Top up your brand balance via the Payments page. When a collaboration is agreed upon, funds are held in escrow and released to the creator once deliverables are verified.",
  },
  {
    q: "Can I track the performance of my campaigns?",
    a: "Yes, use the Analytics page to track clicks, conversions, and revenue generated by your creator partnerships. Each campaign also has its own performance summary.",
  },
  {
    q: "How do I upgrade to Premium?",
    a: "Contact us at support@mystorefront.io to discuss upgrading your brand account and unlocking features like the Creator Directory, Messaging, and Paid Collabs.",
  },
];

export default function BrandHelp() {
  const navigate = useNavigate();
  const { user, loading: authLoading } = useAuth();
  const { role, loading: roleLoading } = useUserRole();
  const { brand, loading: brandLoading } = useBrandAccount();

  useEffect(() => {
    if (!authLoading && !user) navigate("/auth");
  }, [user, authLoading, navigate]);

  useEffect(() => {
    if (!roleLoading && role && role !== "brand" && role !== "admin") navigate("/");
  }, [role, roleLoading, navigate]);

  if (authLoading || roleLoading || brandLoading) {
    return (
      <BrandLayout>
        <div className="flex items-center justify-center py-32">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      </BrandLayout>
    );
  }

  return (
    <BrandLayout brandName={brand?.name} brandStatus={brand?.status} brandPlan={brand?.plan_tier}>
      <div className="space-y-10">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-semibold text-foreground tracking-tight">Help Center</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Everything you need to get the most out of MyStorefront as a brand.
          </p>
        </div>

        {/* Guides grid */}
        <div className="grid gap-4 sm:grid-cols-2">
          {guides.map((guide, i) => (
            <motion.div
              key={guide.title}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.03, duration: 0.25 }}
            >
              <Card className="h-full border-border/60 shadow-none hover:border-border transition-colors">
                <CardContent className="p-5 space-y-3">
                  <div className="flex items-center gap-3">
                    <div className="h-8 w-8 rounded-lg bg-muted flex items-center justify-center shrink-0">
                      <guide.icon className="h-4 w-4 text-muted-foreground" />
                    </div>
                    <div className="min-w-0">
                      <h3 className="text-sm font-semibold text-foreground leading-tight">{guide.title}</h3>
                      <p className="text-xs text-muted-foreground truncate">{guide.description}</p>
                    </div>
                  </div>
                  <ul className="space-y-1.5 pl-0.5">
                    {guide.items.map((item, j) => (
                      <li key={j} className="flex items-start gap-2 text-[13px] text-muted-foreground leading-snug">
                        <ArrowRight className="h-3 w-3 mt-[3px] shrink-0 text-muted-foreground/50" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* FAQs */}
        <div>
          <h2 className="text-base font-semibold text-foreground flex items-center gap-2 mb-3">
            <HelpCircle className="h-4 w-4" />
            Frequently Asked Questions
          </h2>
          <div className="grid gap-3 sm:grid-cols-2">
            {faqs.map((faq, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 + i * 0.03, duration: 0.25 }}
              >
                <Card className="h-full border-border/60 shadow-none">
                  <CardContent className="p-5">
                    <h3 className="text-sm font-medium text-foreground mb-1">{faq.q}</h3>
                    <p className="text-[13px] text-muted-foreground leading-relaxed">{faq.a}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Contact CTA */}
        <Card className="border-dashed border-border/60 shadow-none">
          <CardContent className="py-8 flex flex-col items-center gap-2 text-center">
            <Mail className="h-5 w-5 text-muted-foreground" />
            <p className="text-sm text-muted-foreground">Still need help?</p>
            <a
              href="mailto:support@mystorefront.io"
              className="text-sm font-medium text-foreground hover:underline underline-offset-4"
            >
              support@mystorefront.io
            </a>
          </CardContent>
        </Card>
      </div>
    </BrandLayout>
  );
}
